name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["💻 aspect: code", "🛠 goal: fix", "🚦 status: awaiting triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: detailed-description
    attributes:
      label: Detailed Description
      description: Add a detailed description of the bug report.
      placeholder: A detailed description of the bug report.
      value: "I found this error in this project where ..."
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should be expected?
      value: "I expected that..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: How can someone reproduce the behavior?
      description: Steps to reproduce the behavior you were facing.
      placeholder: How can someone reproduce the behavior you were facing?
      value: |
        1. Go to...
        2. Do...
        3. Now...
        4. Finally...
    validations:
      required: true

  - type: checkboxes
    id: contributing
    attributes:
      label: Contributing
      description: You accept that you've read the [contributing guidelines](https://github.com/web3community/DEV-NFT/blob/main/CONTRIBUTING.md)
      options:
        - label: I have read the project's contribution guidelines.
          required: true

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/web3community/DEV-NFT/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
