# Automation to mark inactive issues/prs as stale

name: Mark Stale Issues/PRs

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    if: github.repository_owner == 'web3community'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue message'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-issue-activity'
        days-before-stale: 14
        days-before-close: 14
